// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'symbol.dart';

// **************************************************************************
// CombinationsGenerator
// **************************************************************************

const SymbolCombinations = <PropheciesRange, SymbolCombination>{
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.YellowSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Beryl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.YellowSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlackPearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Aquamarine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Citrine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Beryl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amber,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Pearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Beryl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Aquamarine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Citrine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Garnet,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Carbuncle,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.RedSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Amber,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlackPearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.RedSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amber,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Carbuncle,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Garnet,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.YellowSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlueSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Ruby,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlueSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlackPearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Carbuncle,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Emerald,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Ruby,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Carbuncle,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Carbuncle,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Amber,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Aquamarine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Citrine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Ruby,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Aquamarine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlackPearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Citrine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Citrine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Amber,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.RedSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.YellowSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlueSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Ruby,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlackPearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Ruby,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Aquamarine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Zircon,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Emerald,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Emerald,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.YellowSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Onyx,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Topaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.RedSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Ruby,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlueSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Aquamarine,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlackPearl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.OrangeTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Beryl,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlackTopaz,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Garnet,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Diamond,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Alexandrite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Amethyst,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Emerald,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Opal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.RedTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.FireOpal,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.PurpleSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Garnet,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.RedSpinel,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Peridot,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Chrysolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Rhodolite,
    colors: ["red", "yellow", "orange"],
    tarrot: TarrotMajor.TheMoon,
  ),
};
